# AWS EKS specific deployment configuration
# This file contains AWS-specific configurations for EKS deployment

# Service with AWS Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: frontend-aws-lb
  namespace: kube-credential
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend
---
# AWS EBS Storage Class for persistent volumes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
# Modified PVC for AWS EBS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: issuance-data-pvc-aws
  namespace: kube-credential
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: aws-ebs-gp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verification-data-pvc-aws
  namespace: kube-credential
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: aws-ebs-gp3