# Credential Issuance Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuance-service
  namespace: kube-credential
  labels:
    app: issuance-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issuance-service
  template:
    metadata:
      labels:
        app: issuance-service
        tier: backend
    spec:
      containers:
      - name: issuance-service
        image: kube-credential/issuance-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: kube-credential-config
              key: NODE_ENV
        - name: SERVICE_NAME
          value: "issuance-service"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: issuance-data-pvc
      restartPolicy: Always
---
# Credential Issuance Service
apiVersion: v1
kind: Service
metadata:
  name: issuance-service
  namespace: kube-credential
  labels:
    app: issuance-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: issuance-service