# Credential Verification Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-service
  namespace: kube-credential
  labels:
    app: verification-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verification-service
  template:
    metadata:
      labels:
        app: verification-service
        tier: backend
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: verification-service
        image: kubecredentialacr.azurecr.io/verification-service:v1
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: kube-credential-config
              key: NODE_ENV
        - name: SERVICE_NAME
          value: "verification-service"
        - name: ISSUANCE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: kube-credential-config
              key: ISSUANCE_SERVICE_URL
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: verification-data-pvc
      restartPolicy: Always
---
# Credential Verification Service
apiVersion: v1
kind: Service
metadata:
  name: verification-service
  namespace: kube-credential
  labels:
    app: verification-service
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: verification-service